[project]
name = "enzax"
version = "0.1.0"
description = "Differentiable models of enzyme-catalysed reaction networks"
authors = [
    {name = "Teddy Groves", email = "tedgro@dtu.dk"},
]
dependencies = [
    "blackjax>=1.2.1",
    "pydantic>=2.8.2",
    "diffrax>=0.6.0",
    "chex>=0.1.86",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pdm]
distribution = true
