# This workflow tests whether the documentation builds correctly and runs a
# lighthouse audit.

name: Docs check

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: install enzax with development packages
      run: pip install -e .\[docs\]
    - name: build docs with mkdocs
      run: mkdocs build
    - name: Audit with Lighthouse
      uses: treosh/lighthouse-ci-action@v12
      with:
        configPath: ".github/workflows/lighthouserc.json"
        temporaryPublicStorage: true
        uploadArtifacts: true
        runs: 3 # Multiple runs to reduce variance
